export const SET_COUNTRIES = "SET_COUNTRIES";
export const SET_REGION_FILTERS = "SET_REGION_FILTERS";
export const IS_FETCHING_COUNTRIES = "IS_FETCHING_COUNTRIES";
export const IS_MOBILE_MENU_OPEN = "IS_MOBILE_MENU_OPEN";
export const ACTIVE_FILTER = "ACTIVE_FILTER";